[project]
name = "chorms"
version = "0.1.4"
description = "Model on household norms and chores"
readme = "README.md"
authors = [
    { name = "ThomasHjorgensen", email = "tjo@econ.ku.dk" }
]
requires-python = ">=3.12"

[project.scripts]
chorms = "chorms:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "scipy>=1.18.0",
]
